Add Cyber Testnet
ethereum-optimism/superchain-registry pull request #624
Opened 2024-10-08 15:45 UTC by atenjin

# Adding a New Chain
This PR adds Cyber Testnet to the registry.

## Checklist
- [x] I have declared the chain at the appropriate [Superchain Level](../docs/glossary.md#superchain-level-and-rollup-stage).
- [x] I have run `just validate <chain-id>` locally to ensure all local validation checks pass. 
- [x] I have run `just codegen` to ensure that the chainlist and other generated files are up-to-date and include my chain.

2024-10-16 16:57 UTC, parkgunou reviewed
Hey, not sure whether the `superchain/configs/mainnet/cyber.yaml` file should be included in this PR.

2024-10-16 17:52 UTC, parkgunou approved these changes

2024-10-17 14:35 UTC, sbvegan requested changes
Please remove:

- superchain/configs/sepolia/cyber.toml
- superchain/extra/genesis-system-configs/mainnet/cyber.json
- superchain/extra/genesis/mainnet/cyber.json.gz

Then run `just codegen` again to make sure this is a clean commit of just cyber testnet

2024-10-21 14:03 UTC, sbvegan approved these changes

2024-10-21 15:12 UTC, merged