Add Swell (Testnet)
ethereum-optimism/superchain-registry pull request #690
Opened 2024-11-18 15:29 UTC by atenjin

# Adding a New Chain
This PR adds Swell Testnet to the registry.

## Checklist
- [x] I have declared the chain at the appropriate [Superchain Level](../docs/glossary.md#superchain-level-and-rollup-stage).
- [x] I have run `just validate <chain-id>` locally to ensure all local validation checks pass. 
- [x] I have run `just codegen` to ensure that the chainlist and other generated files are up-to-date and include my chain.

2024-12-10 20:19 UTC, Wazabie approved these changes

2024-12-18 21:18 UTC, sigma approved these changes

2024-12-19 13:20 UTC, sigma requested changes
Looks like this doesn't apply cleanly to main anymore

- `just codegen` adds a "governed_by_optimism" flag
- `just validate 1924` throws some errors:

```
=== RUN   TestValidation/Swellchain_Testnet_(1924)/Data_Availability_Type
    data-availability-type_test.go:56:
                Error Trace:   .../github.com/ethereum-optimism/superchain-registry/validation/data-availability-type_test.go:56
                                                        .../github.com/ethereum-optimism/superchain-registry/validation/validation_test.go:44
                Error:          Received unexpected error:
                                operation failed permanently after 3 attempts: failed to retrieve previous nonce: missing trie node 486e81dbaf0d082af8a24573c8588c9db1fe72046a2a50fc5938baf82a3a18d0 (path ) state 0x486e81dbaf0d082af8a24573c8588c9db1fe72046a2a50fc5938baf82a3a18d0 is not available
                Test:           TestValidation/Swellchain_Testnet_(1924)/Data_Availability_Type
                Messages:       failed when checking chain for recent batcher txs from 0x77C60EfDBDa83410EE0373Eda2ed06891238c93d
--- FAIL: TestValidation/Swellchain_Testnet_(1924)/Data_Availability_Type (3.97s)
```

2025-01-17 19:03 UTC, mslipper requested changes
This PR is missing some key addresses from `addresses.json` like `L1CrossDomainMessenger`. Can you please add these addresses?

2025-01-20 20:44 UTC, Wazabie commented
> This PR is missing some key addresses from `addresses.json` like `L1CrossDomainMessenger`. Can you please add these addresses?

@atenjin please see the above

2025-01-29 03:13 UTC, atenjin commented
> > This PR is missing some key addresses from `addresses.json` like `L1CrossDomainMessenger`. Can you please add these addresses?
> 
> @atenjin please see the above

I just follow the readme introduction to execute, I do not know why missed those address.
I can do rebase and generate everything again, if it still miss those file, can you help me to find the reason?

2025-01-30 11:47 UTC, atenjin commented
> > This PR is missing some key addresses from `addresses.json` like `L1CrossDomainMessenger`. Can you please add these addresses?
> 
> @atenjin please see the above

Hello, when I try to do the rebase on the newest main branch, then I noticed that in your doc all operations are changed.

But when I plan to follow the doc to execute one by one, at first step I meet the error:

![image](https://github.com/user-attachments/assets/df4a9c20-36f4-4002-96bf-dfb4dee993b5)

2025-01-30 11:50 UTC, Wazabie commented
@mslipper do we need to validate also this one against the old SCR? (I believe @atenjin might also have other legacy chains that didn't use op-deployer)

2025-01-31 01:06 UTC, atenjin commented
> @mslipper do we need to validate also this one against the old SCR? (I believe @atenjin might also have other legacy chains that didn't use op-deployer)

By the way, the swell-testnet is using op-deployer tool, which is a very early time.

2025-01-31 16:37 UTC, sbvegan commented
Some of these checks can probably be passed by making sure you order the swell.toml file in alphabetical order and then run `just codegen` again

2026-04-27 14:16 UTC, closed without merging